name: "Deploy"
on:
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      k8s-release-name:
        required: false
        type: string
      k8s-namespace:
        required: false
        type: string
      deploy-solr-image:
        description: "Used if you have a solr image to deploy"
        required: false
        type: boolean
      tag:
        description: "Tag to override default of current branch sha"
        required: false
        type: string
  workflow_call:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      k8s-release-name:
        required: false
        type: string
      k8s-namespace:
        required: false
        type: string
      deploy-solr-image:
        description: "Used if you have a solr image to deploy"
        required: false
        type: boolean
      tag:
        description: "Tag to override default of current branch sha"
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  deployment:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.9.4
    environment: ${{ inputs.environment }}
    env:
      HELM_EXPERIMENTAL_OCI: 1
      HELM_RELEASE_NAME: ${{ github.event.repository.name }}-${{ inputs.environment }}
      KUBE_NAMESPACE: ${{ github.event.repository.name }}-${{ inputs.environment }}
      HELM_EXTRA_ARGS: >
        --values ops/${{ inputs.environment }}-deploy.yaml
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      ENVCONFIG_FILE: ${{ secrets.ENVCONFIG_FILE }}
      KUBECONFIG: ./kubeconfig.yml
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@testing-deploy-env-vars
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Do deploy with solr image
        if: ${{ inputs.deploy-solr-image }}
        run: |
          export DEPLOY_TAG=${TAG};
          export DEPLOY_IMAGE=ghcr.io/${REPO_LOWER};
          export WORKER_IMAGE=ghcr.io/${REPO_LOWER}/worker;
          export SOLR_IMAGE=ghcr.io/${REPO_LOWER}/solr;
          ./bin/helm_deploy ${{ inputs.k8s-release-name || format('{0}-{1}', github.event.repository.name, inputs.environment) }} ${{ inputs.k8s-namespace || format('{0}-{1}', github.event.repository.name, inputs.environment) }}
      - name: Do deploy
        if: ${{ inputs.deploy-solr-image }} == 'false'
        run: |
          export DEPLOY_TAG=${TAG};
          export DEPLOY_IMAGE=ghcr.io/${REPO_LOWER};
          export WORKER_IMAGE=ghcr.io/${REPO_LOWER}/worker;
          ./bin/helm_deploy ${{ inputs.k8s-release-name || format('{0}-{1}', github.event.repository.name, inputs.environment) }} ${{ inputs.k8s-namespace || format('{0}-{1}', github.event.repository.name, inputs.environment) }}
