name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      base:
        required: false
        type: boolean
      subdir:
        default: '.'
        type: string
      solr:
        required: false
        type: boolean
      tag:
        required: false
        type: string
      web:
        required: false
        type: boolean
      worker:
        required: false
        type: boolean
  workflow_call:
    inputs:
      base:
        required: false
        type: boolean
      subdir:
        default: '.'
        type: string
      solr:
        required: false
        type: boolean
      tag:
        required: false
        type: string
      web:
        required: false
        type: boolean
      worker:
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v0.0.11
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull base image to prevent build
        if: ${{ inputs.base }}
        run: >-
          cd ${{ inputs.subdir }};
          docker-compose pull base
      - name: Pull solr image to prevent build
        if: ${{ inputs.solr }}
        run: >-
          cd ${{ inputs.subdir }};
          docker-compose pull solr
      - name: Pull web image to prevent build
        if: ${{ inputs.web }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          docker-compose pull web
      - name: Pull worker image to prevent build
        if: ${{ inputs.worker }}
        run: >-
          cd ${{ inputs.subdir }};
          docker-compose pull worker
      - name: Run Rubocop
        run: >-
          cd ${{ inputs.subdir }};
          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb;
          docker-compose run web bundle exec rubocop --parallel --format progress
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
